import { Injectable } from '@angular/core';
import { Product } from '../models/product';
import { Category } from '../enums/category';
import { Subcategory } from '../enums/subcategory';
import { Size } from '../enums/size';

@Injectable({
  providedIn: 'root',
})
export class ProductsDataService {

 productsInStock: Product[] = [
  {
    id: 1,
    name: 'Classic White T-shirt',
    imgURl: "assets/images/product-img/image%20(1).png",
    category: Category.Men,
    subcategory: Subcategory.Tshirt,
    price: 19.99,
    sizes: [Size.Small, Size.Medium],
  },
  {
    id: 2,
    name: 'Dark Wash Skinny Jeans',
    imgURl: "assets/images/product-img/image%20(2).png",
    category: Category.Men,
    subcategory: Subcategory.Jeans,
    price: 59.99,
    sizes: [Size.Medium, Size.Large],
  },
  {
    id: 3,
    name: 'Summer Shorts',
    imgURl: "assets/images/product-img/image%20(3).png",
    category: Category.Men,
    subcategory: Subcategory.Shorts,
    price: 29.99,
    sizes: [Size.Small, Size.Large],
  },
  {
    id: 4,
    name: 'Floral Print Dress',
    imgURl: "assets/images/product-img/image%20(4).png",
    category: Category.Women,
    subcategory: Subcategory.Dresses,
    price: 39.99,
    sizes: [Size.Small, Size.Medium],
  },
  {
    id: 5,
    name: 'Leather Jacket',
    imgURl: "assets/images/product-img/image%20(5).png",
    category: Category.Women,
    subcategory: Subcategory.Jackets,
    price: 79.99,
    sizes: [Size.Medium, Size.Large],
  },
  {
    id: 6,
    name: 'Running Shoes',
    imgURl: "assets/images/product-img/image%20(6).png",
    category: Category.Women,
    subcategory: Subcategory.Shoes,
    price: 49.99,
    sizes: [Size.Small, Size.Medium],
  },
  {
    id: 7,
    name: 'Striped Polo Shirt',
    imgURl: "assets/images/product-img/image%20(7).png",
    category: Category.Men,
    subcategory: Subcategory.Tshirt,
    price: 24.99,
    sizes: [Size.Medium, Size.Large],
  },
  {
    id: 8,
    name: 'Ripped Denim Shorts',
    imgURl: "assets/images/product-img/image%20(8).png",
    category: Category.Men,
    subcategory: Subcategory.Shorts,
    price: 34.99,
    sizes: [Size.Small, Size.Medium],
  },
  {
    id: 9,
    name: 'Maxi Evening Gown',
    imgURl: "assets/images/product-img/image%20(9).png",
    category: Category.Women,
    subcategory: Subcategory.Dresses,
    price: 89.99,
    sizes: [Size.Small, Size.Large],
  },
  {
    id: 10,
    name: 'Hiking Boots',
    imgURl: "assets/images/product-img/image%20(10).png",
    category: Category.Men,
    subcategory: Subcategory.Shoes,
    price: 69.99,
    sizes: [Size.Medium, Size.XLarge],
  },
  {
    id: 11,
    name: 'Graphic Print T-shirt',
    imgURl: "assets/images/product-img/image%20(11).png",
    category: Category.Men,
    subcategory: Subcategory.Tshirt,
    price: 22.99,
    sizes: [Size.Small, Size.Large],
  },
  {
    id: 12,
    name: 'Slim Fit Chinos',
    imgURl: "assets/images/product-img/image%20(12).png",
    category: Category.Men,
    subcategory: Subcategory.Tshirt,
    price: 44.99,
    sizes: [Size.Medium, Size.XLarge],
  },
  {
    id: 13,
    name: 'Beach Board Shorts',
    imgURl: "assets/images/product-img/image%20(13).png",
    category: Category.Men,
    subcategory: Subcategory.Shorts,
    price: 26.99,
    sizes: [Size.Small, Size.Large],
  },
  {
    id: 14,
    name: 'Bohemian Maxi Dress',
    imgURl: "assets/images/product-img/image%20(14).png",
    category: Category.Women,
    subcategory: Subcategory.Dresses,
    price: 49.99,
    sizes: [Size.Medium, Size.Large],
  },
  {
    id: 15,
    name: 'Bomber Jacket',
    imgURl: "assets/images/product-img/image%20(15).png",
    category: Category.Women,
    subcategory: Subcategory.Jackets,
    price: 59.99,
    sizes: [Size.Medium, Size.XLarge],
  },
  {
    id: 16,
    name: 'Canvas Slip-on Shoes',
    imgURl: "assets/images/product-img/image%20(16).png",
    category: Category.Women,
    subcategory: Subcategory.Shoes,
    price: 34.99,
    sizes: [Size.Small, Size.Medium],
  },
  {
    id: 17,
    name: 'V-neck Sweater',
    imgURl: "assets/images/product-img/image%20(17).png",
    category: Category.Men,
    subcategory: Subcategory.Tshirt,
    price: 39.99,
    sizes: [Size.Medium, Size.Large],
  },
  {
    id: 18,
    name: 'Cargo Shorts',
    imgURl: "assets/images/product-img/image%20(18).png",
    category: Category.Men,
    subcategory: Subcategory.Shorts,
    price: 31.99,
    sizes: [Size.Small, Size.Medium],
  },
  {
    id: 19,
    name: 'Cocktail Party Dress',
    imgURl: "assets/images/product-img/image%20(19).png",
    category: Category.Women,
    subcategory: Subcategory.Dresses,
    price: 59.99,
    sizes: [Size.Small, Size.Large],
  },
  {
    id: 20,
    name: 'Leather Moto Jacket',
    imgURl: "assets/images/product-img/image%20(20).png",
    category: Category.Women,
    subcategory: Subcategory.Jackets,
    price: 89.99,
    sizes: [Size.Medium, Size.XLarge],
  },
  {
    id: 21,
    name: 'Sweat-wicking Running Shoes',
    imgURl: "assets/images/product-img/image%20(21).png",
    category: Category.Women,
    subcategory: Subcategory.Shoes,
    price: 54.99,
    sizes: [Size.Small, Size.Medium],
  },
  {
    id: 22,
    name: 'Henley Neck T-shirt',
    imgURl: "assets/images/product-img/image%20(22).png",
    category: Category.Men,
    subcategory: Subcategory.Tshirt,
    price: 27.99,
    sizes: [Size.Medium, Size.Large],
  },
  {
    id: 23,
    name: 'Relaxed Fit Jeans',
    imgURl: "assets/images/product-img/image%20(23).png",
    category: Category.Men,
    subcategory: Subcategory.Jeans,
    price: 49.99,
    sizes: [Size.Medium, Size.XLarge],
  },
  {
    id: 24,
    name: 'Athletic Training Shorts',
    imgURl: "assets/images/product-img/image%20(24).png",
    category: Category.Men,
    subcategory: Subcategory.Shorts,
    price: 34.99,
    sizes: [Size.Small, Size.Medium],
  },
  {
    id: 25,
    name: 'Wrap Midi Dress',
    imgURl: "assets/images/product-img/image%20(25).png",
    category: Category.Women,
    subcategory: Subcategory.Dresses,
    price: 44.99,
    sizes: [Size.Small, Size.Large],
  },
  {
    id: 26,
    name: 'Quilted Puffer Jacket',
    imgURl: "assets/images/product-img/image%20(26).png",
    category: Category.Women,
    subcategory: Subcategory.Jackets,
    price: 79.99,
    sizes: [Size.Medium, Size.XLarge],
  },
  {
    id: 27,
    name: 'Classic Loafers',
    imgURl: "assets/images/product-img/image%20(27).png",
    category: Category.Women,
    subcategory: Subcategory.Shoes,
    price: 64.99,
    sizes: [Size.Small, Size.Medium],
  },
  {
    id: 28,
    name: 'Crew Neck Sweatshirt',
    imgURl: "assets/images/product-img/image%20(28).png",
    category: Category.Men,
    subcategory: Subcategory.Tshirt,
    price: 29.99,
    sizes: [Size.Medium, Size.Large],
  },
  {
    id: 29,
    name: 'Chino Bermuda Shorts',
    imgURl: "assets/images/product-img/image%20(29).png",
    category: Category.Men,
    subcategory: Subcategory.Shorts,
    price: 39.99,
    sizes: [Size.Small, Size.Medium],
  },
  {
    id: 30,
    name: 'Off-Shoulder Maxi Dress',
    imgURl: "assets/images/product-img/image%20(30).png",
    category: Category.Women,
    subcategory: Subcategory.Dresses,
    price: 54.99,
    sizes: [Size.Small, Size.Large],
  },
];
}
